version: '3.8'
services:
  web:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
    volumes:
      - ./backend/app:/app/app:ro
      - ./backend/model.joblib:/app/model.joblib:ro